name: Build and Push Docker Image with Checkov

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: im-lab-git/vul-node-owasp-app-25

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Prisma Cloud Checkov
        id: prisma-cloud-iac
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.sg.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          skip_results_upload: false # Set to false will stop upload to result to Prisma Cloud Portal
          directory: .
          download_external_modules: true
          framework: "all"
          soft_fail: true # Only show the error with out stopping the Pipeline
          # hard_fail_on: "CRITICAL" # If any Critical findings, fail the step to stop the pipeline

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI # <- IMPORTANT!!! Make sure the cli is installed before using the action
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jyheroku25vulnode" #Must be unique in Heroku
          heroku_email: "jasmdasdingrhkjam@gmail.com"
